all:
  hosts:
    master1:
      ansible_host: 192.168.100.123
      ip: 192.168.100.123
      access_ip: 192.168.100.123
    worker1:
      ansible_host: 192.168.100.203
      ip: 192.168.100.203
      access_ip: 192.168.100.203
  children:
    kube_control_plane:
      hosts:
        master1:
    kube_node:
      hosts:
        worker1:
    etcd:
      hosts:
        master1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
